working_directory = 'D:\'

live_config_reload = true

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]	
save_to_clipboard = true

[window]
dynamic_title = false
opacity = 0.9
dynamic_padding = true

decorations = "ButtonLess"

[window.padding]
x = 15
y = 15

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0

[font]
normal.family = "Hack Nerd Font"
size = 11.0

[colors.primary]
background = '0x14191f'     
foreground = '0xeffbff' 

[colors.normal]
black = '0x516a88'
red = '0x7a9bc2'
green = '0x95CC5E'
yellow = '0x748aa6'
blue = '0x267fb5'
magenta = '0x4cbbff'
cyan = '0x6ee2ff'
white = '0xeffbff'

[colors.bright]
black = '0x516a88'
red = '0x7a9bc2'
green = '0x95CC5E'
yellow = '0x748aa6'
blue = '0x267fb5'
magenta = '0x4cbbff'
cyan = '0x6ee2ff'
white = '0xeffbff'

[colors.cursor]
text = '0x14191f'           
cursor = '0x267fb5'         

[colors.selection]
text = '0xeffbff'           
background = '0x267fb5'
